version: '3'

tasks:
  dev:
    desc: Start Go backend
    deps:
      - install-backend
    env:
      ENV: development
      PORT: 3000
      DATABASE_USER: kumapush
      DATABASE_PASSWORD: thisisasupersecretpasswordnoonewilleverbeabletoguess
      DATABASE_NAME: kumapush
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
    dotenv: ['.env']
    cmds:
      - go run main.go

  install-backend:
    internal: true
    sources:
      - go.mod
      - go.sum
    cmds:
      - go mod download

  db:up:
    desc: Start PostgreSQL database
    cmds:
      - docker compose -f docker-compose-deps.yml up -d

  db:down:
    desc: Stop PostgreSQL database
    cmds:
      - docker compose -f docker-compose-deps.yml down

  db:migration:
    desc: 'Create a new SQL migration, e.g. task db:migration -- add_devices_name'
    cmds:
      - go run github.com/pressly/goose/v3/cmd/goose@v3.28.0 -s -dir db/migrations create {{.CLI_ARGS}} sql
